spring:
  application:
    name: blackrock-auto-savings-challenge

server:
  port: 5477


logging:
  #    file:
  #      path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #      file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error


management:
  endpoints:
    web:
      exposure:
        include: health,metrics

#swagger
springdoc:
  swagger-ui:
    display-request-duration: true
    try-it-out-enabled: true
    with-credentials: true